# const.gd
class_name Consts

const MISSILE_SLOT_COUNT: int = 3

const MISSILE_PUZZLE_BOARD_GRID_WIDTH: int = 18
const MISSILE_PUZZLE_BOARD_GRID_HEIGHT: int = 12
const MISSILE_PUZZLE_BOARD_CELL_SIZE: int = 32